#!/bin/bash
#
# Check that server is listening on 443
#

source /usr/local/status/lib/status
[[ $? -ne 0 ]] && exit 1


function check
{
    status.log "[INFO] Checking if port 443 is opened"
    nc -nz 0 443 && status.set $STATUS_OK || status.set $STATUS_ERROR
}

status.run check
